### ISSUE TITLE
Having issues installing fiona from conda-forge, looks related to conda-forge gdal install

### ISSUE THREAD

**Issue by nickeubank** [conda-forge/fiona-feedstock#1]
Can't seem to get a working `conda` build of fiona in a development environment in osx (works fine in root environment). I *think* it's a gdal issue. Here's the output:

    conda create -y --name test_fiona3 python=3.4
    Fetching package metadata: ....
    Solving package specifications: .........

    Package plan for installation in environment /Users/Nick/anaconda/envs/test_fiona3:

    The following NEW packages will be INSTALLED:

        openssl:    1.0.2g-0      defaults
        pip:        8.1.1-py34_0  defaults
        python:     3.4.4-0       defaults
        readline:   6.2-2         defaults
        setuptools: 20.3-py34_0   defaults
        sqlite:     3.9.2-0       defaults
        tk:         8.5.18-0      defaults
        wheel:      0.29.0-py34_0 defaults
        xz:         5.0.5-1       defaults
        zlib:       1.2.8-0       defaults

    Linking packages ...
    [      COMPLETE      ]|#############################################################################################| 100%
    #
    # To activate this environment, use:
    # $ source activate test_fiona3
    #
    # To deactivate this environment, use:
    # $ source deactivate
    #
    ➜  ~ source activate test_fiona3
    discarding /Users/Nick/anaconda/bin from PATH
    prepending /Users/Nick/anaconda/envs/test_fiona3/bin to PATH
    (test_fiona3)➜  ~ conda install -y -c conda-forge fiona
    Fetching package metadata: ......
    Solving package specifications: .........

    Package plan for installation in environment /Users/Nick/anaconda/envs/test_fiona3:

    The following NEW packages will be INSTALLED:

        click:         6.3-py34_0         defaults   
        click-plugins: 1.0.3-py34_0       conda-forge
        cligj:         0.4.0-py34_0       defaults   
        curl:          7.45.0-0           defaults   
        fiona:         1.6.3-np110py34_0  conda-forge
        gdal:          1.11.4-np110py34_0 conda-forge
        geos:          3.4.2-0            conda-forge
        hdf4:          4.2.11-0           defaults   
        hdf5:          1.8.15.1-2         defaults   
        jbig:          2.1-0              defaults   
        jpeg:          8d-1               defaults   
        kealib:        1.4.5-0            defaults   
        krb5:          1.13.2-0           defaults   
        libnetcdf:     4.3.3.1-3          defaults   
        libpng:        1.6.17-0           defaults   
        libtiff:       4.0.6-1            defaults   
        mkl:           11.3.1-0           defaults   
        munch:         2.0.4-py34_0       conda-forge
        numpy:         1.10.4-py34_0      defaults   
        openjpeg:      2.1.0-1            conda-forge
        proj.4:        4.9.1-2            conda-forge
        six:           1.10.0-py34_0      defaults   
        xerces-c:      3.1.2-0            defaults   

    Linking packages ...
    [      COMPLETE      ]|#############################################################################################| 100%
    (test_fiona3)➜  ~ python -c 'import fiona'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/Nick/anaconda/envs/test_fiona3/lib/python3.4/site-packages/fiona/__init__.py", line 72, in <module>
        from fiona.collection import Collection, BytesCollection, vsi_path
      File "/Users/Nick/anaconda/envs/test_fiona3/lib/python3.4/site-packages/fiona/collection.py", line 7, in <module>
        from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
    ImportError: dlopen(/Users/Nick/anaconda/envs/test_fiona3/lib/python3.4/site-packages/fiona/ogrext.so, 2): Library not loaded: /usr/local/lib/libgif.4.1.6.dylib
      Referenced from: /Users/Nick/anaconda/envs/test_fiona3/lib/libgdal.1.dylib
      Reason: image not found
    (test_fiona3)➜  ~ 

Any thoughts? [Cross-listed in gdal-feedstock](https://github.com/conda-forge/gdal-feedstock/issues/16), since looks gdal related...

**Comment by pelson** [comment]
Looks like ```ogrext.so``` is referencing a file ```/usr/local/lib/libgif```. @conda-forge/gdal - maybe a libgif feedstock is needed?

**Comment by ocefpaf** [comment]
@nickeubank I created a package for `libgif` and added as a dependency for fiona (although I just realized that should be in `gdal`, but I will leave that for later.)

Can you test that and get report back here if that solves the issue for you?

**Comment by nickeubank** [comment]
Excuse my ignorance, but how do I get the new recipe to load? I rad it as before (output below) but am not seeing `libgif` in installed packages (and it still fails).

        (test_fiona3)➜  ~ conda create -y --name test_fiona5 python=3.4
	Fetching package metadata: ....
	Solving package specifications: .........

	Package plan for installation in environment /Users/Nick/anaconda/envs/test_fiona5:

	The following NEW packages will be INSTALLED:

	    openssl:    1.0.2g-0      defaults
	    pip:        8.1.1-py34_0  defaults
	    python:     3.4.4-0       defaults
	    readline:   6.2-2         defaults
	    setuptools: 20.3-py34_0   defaults
	    sqlite:     3.9.2-0       defaults
	    tk:         8.5.18-0      defaults
	    wheel:      0.29.0-py34_0 defaults
	    xz:         5.0.5-1       defaults
	    zlib:       1.2.8-0       defaults

	Linking packages ...
	[      COMPLETE      ]|###################################################| 100%
	#
	# To activate this environment, use:
	# $ source activate test_fiona5
	#
	# To deactivate this environment, use:
	# $ source deactivate
	#
	(test_fiona3)➜  ~ source activate test_fiona5
	discarding /Users/Nick/anaconda/envs/test_fiona3/bin from PATH
	prepending /Users/Nick/anaconda/envs/test_fiona5/bin to PATH
	(test_fiona5)➜  ~ conda install -y -c conda-forge fiona
	Fetching package metadata: ......
	Solving package specifications: .........

	Package plan for installation in environment /Users/Nick/anaconda/envs/test_fiona5:

	The following packages will be downloaded:

	    package                    |            build
	    ---------------------------|-----------------
	    gdal-1.11.4                |      np110py34_1        13.4 MB  conda-forge

	The following NEW packages will be INSTALLED:

	    click:         6.3-py34_0         defaults   
	    click-plugins: 1.0.3-py34_0       conda-forge
	    cligj:         0.4.0-py34_0       defaults   
	    curl:          7.45.0-0           defaults   
	    fiona:         1.6.3-np110py34_1  conda-forge
	    gdal:          1.11.4-np110py34_1 conda-forge
	    geos:          3.4.2-0            conda-forge
	    giflib:        5.1.2-0            conda-forge
	    hdf4:          4.2.11-0           defaults   
	    hdf5:          1.8.15.1-2         defaults   
	    jbig:          2.1-0              defaults   
	    jpeg:          8d-1               defaults   
	    kealib:        1.4.5-0            defaults   
	    krb5:          1.13.2-0           defaults   
	    libgcc:        4.8.5-1            defaults   
	    libnetcdf:     4.3.3.1-3          defaults   
	    libpng:        1.6.17-0           defaults   
	    libtiff:       4.0.6-1            defaults   
	    mkl:           11.3.1-0           defaults   
	    munch:         2.0.4-py34_0       conda-forge
	    numpy:         1.10.4-py34_0      defaults   
	    openjpeg:      2.1.0-1            conda-forge
	    proj.4:        4.9.1-2            conda-forge
	    six:           1.10.0-py34_0      defaults   
	    xerces-c:      3.1.2-0            defaults   

	Fetching packages ...
	gdal-1.11.4-np 100% |################################| Time: 0:00:02   5.61 MB/s
	Extracting packages ...
	[      COMPLETE      ]|###################################################| 100%
	Linking packages ...
	[      COMPLETE      ]|###################################################| 100%
	(test_fiona5)➜  ~ python -c 'import fiona'
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/Users/Nick/anaconda/envs/test_fiona5/lib/python3.4/site-packages/fiona/__init__.py", line 72, in <module>
	    from fiona.collection import Collection, BytesCollection, vsi_path
	  File "/Users/Nick/anaconda/envs/test_fiona5/lib/python3.4/site-packages/fiona/collection.py", line 7, in <module>
	    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
	ImportError: dlopen(/Users/Nick/anaconda/envs/test_fiona5/lib/python3.4/site-packages/fiona/ogrext.so, 2): Library not loaded: /usr/local/lib/libgif.4.1.6.dylib
	  Referenced from: /Users/Nick/anaconda/envs/test_fiona5/lib/libgdal.1.dylib
	  Reason: image not found
	(test_fiona5)➜  ~

**Comment by pelson** [comment]
> Excuse my ignorance, but how do I get the new recipe to load?

You need to make sure you have conda-forge on your channels. My advice:

```
conda config --add channels conda-forge
conda create -y --name test_fiona5 python=3.4 fiona
```

If you don't want to add conda-forge permanently, then:

```
conda create -c conda-forge -y --name test_fiona5 python=3.4 fiona
```

-----

If you already had an environment:

```
conda update --all -n test_fiona2 -c conda-forge
```

**Comment by nickeubank** [comment]
@pelson Great! Works like a charm when I do `conda update --all -n test_fiona5 -c conda-forge` -- `fiona` loads and runs.

One note, which may be a `conda-forge` issue or may be on my side: When I tried `conda config --add channels conda-forge` I get the error:

    ➜  ~ conda config --add channels 'conda-forge' 
    Error: Could not parse the yaml file. Use -f to use the
    yaml parser (this will remove any structure or comments from the existing
    .condarc file). Reason: couldn't parse modified yaml

**Comment by pelson** [comment]
Never seen it, but I guess you have a ```~/.condarc``` which has invalid yaml. Might be worth checking out your config file there.

Thanks for letting us know it worked @nickeubank. And amazing turnaround to rebuild fiona and gdal on easter bank holiday @ocefpaf :rabbit2: :smile: . :+1:

**Comment by nickeubank** [comment]
Here here! Thanks everyone!

**Comment by ocefpaf** [comment]
> One note, which may be a `conda-forge` issue or may be on my side: When I tried `conda config --add channels conda-forge` I get the error:

    ➜  ~ conda config --add channels 'conda-forge' 
    Error: Could not parse the yaml file. Use -f to use the
    yaml parser (this will remove any structure or comments from the existing
    .condarc file). Reason: couldn't parse modified yaml

I always use the force option [1], but it is worth taking a look at your `.condarc` file.

[1] `conda config --add channels conda-forge -f`

**Comment by pelson** [comment]
> I always use the force option [1], but it is worth taking a look at your .condarc file.

Do we need to modify the README.md in the feedstocks to reflect that?

**Comment by ocefpaf** [comment]
We can do that but that is a conda bug IMO.

**Comment by nickeubank** [comment]
Odd followup on this:

When I run 
    
    conda create -y --name test_env1 python=3.4
    source activate test_env1
    conda install fiona -c conda-forge -y
    python -c 'import fiona'

I get: 

       Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "/Users/Nick/anaconda/envs/test_env1/lib/python3.4/site-packages/fiona/__init__.py", line 72, in <module>
       from fiona.collection import Collection, BytesCollection, vsi_path
     File "/Users/Nick/anaconda/envs/test_env1/lib/python3.4/site-packages/fiona/collection.py", line 7, in <module>
       from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
   ImportError: dlopen(/Users/Nick/anaconda/envs/test_env1/lib/python3.4/site-packages/fiona/ogrext.so, 2): Library not loaded: /usr/local/lib/libgif.4.1.6.   dylib
     Referenced from: /Users/Nick/anaconda/envs/test_env1/lib/libgdal.1.dylib
     Reason: image not found


But if I then do:

    conda update --all -n test_env1 -c conda-forge

`Fiona` imports without a problem.

Is there a reason that `update` is loading differently from `install`?

**Comment by ocefpaf** [comment]
> Odd followup on this:
>
> When I run
>
> conda create -y --name test_env1 python=3.4
> source activate test_env1
> conda install fiona -c conda-forge -y
> python -c 'import fiona'
>
> I get:
>
>    Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>  File
"/Users/Nick/anaconda/envs/test_env1/lib/python3.4/site-packages/fiona/__init__.py",
line 72, in <module>
>    from fiona.collection import Collection, BytesCollection, vsi_path
>  File
"/Users/Nick/anaconda/envs/test_env1/lib/python3.4/site-packages/fiona/collection.py",
line 7, in <module>
>    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
>
> ImportError:
dlopen(/Users/Nick/anaconda/envs/test_env1/lib/python3.4/site-packages/fiona/ogrext.so,
2): Library not loaded: /usr/local/lib/libgif.4.1.6. dylib
> Referenced from: /Users/Nick/anaconda/envs/test_env1/lib/libgdal.1.dylib
> Reason: image not found
>
> But if I then do:
>
> conda update --all -n test_env1 -c conda-forge
>
> Fiona imports without a problem.

Can you post the output of conda list before and after the update? Just
want to check what is being installed.

> Is there a reason that update is loading differently from install?

Not sure. I'd expect an updated env already when you created it.

**Comment by nickeubank** [comment]
List after initial installation:

    # packages in environment at /Users/Nick/anaconda/envs/test_env2:
    #
    click                     6.3                      py34_0    defaults
    click-plugins             1.0.3                    py34_0    ioos
    cligj                     0.4.0                    py34_0    defaults
    curl                      7.45.0                        0    defaults
    fiona                     1.6.3               np110py34_1    conda-forge
    gdal                      1.11.4              np110py34_1    conda-forge
    geos                      3.4.2                         1    conda-forge
    giflib                    5.1.2                         0    conda-forge
    hdf4                      4.2.11                        0    defaults
    hdf5                      1.8.15.1                      2    defaults
    jbig                      2.1                           0    defaults
    jpeg                      8d                            1    <unknown>
    kealib                    1.4.5                         0    defaults
    krb5                      1.13.2                        0    defaults
    libgcc                    4.8.5                         1    defaults
    libnetcdf                 4.3.3.1                       3    defaults
    libpng                    1.6.17                        0    <unknown>
    libtiff                   4.0.6                         1    defaults
    mkl                       11.3.1                        0    defaults
    munch                     2.0.4                    py34_0    ioos
    numpy                     1.10.4                   py34_0    defaults
    openjpeg                  2.1.0                         1    conda-forge
    openssl                   1.0.2g                        0    defaults
    pip                       8.1.1                    py34_1    defaults
    proj.4                    4.9.1                         2    conda-forge
    python                    3.4.4                         0    defaults
    readline                  6.2                           2    <unknown>
    setuptools                20.3                     py34_0    defaults
    six                       1.10.0                   py34_0    defaults
    sqlite                    3.9.2                         0    defaults
    tk                        8.5.18                        0    <unknown>
    wheel                     0.29.0                   py34_0    defaults
    xerces-c                  3.1.2                         0    defaults
    xz                        5.0.5                         1    defaults
    zlib                      1.2.8                         0    <unknown>
    
 Change list:

    Package plan for installation in environment /Users/Nick/anaconda/envs/test_env2:
    
    The following NEW packages will be INSTALLED:
    
        libgdal: 2.0.0-0           defaults   
    
    The following packages will be UPDATED:
    
        gdal:    1.11.4-np110py34_1 conda-forge --> 2.0.2-np110py34_1 conda-forge
    
    The following packages will be DOWNGRADED:
    
        cligj:   0.4.0-py34_0       defaults    --> 0.2.0-py34_0      defaults   
        fiona:   1.6.3-np110py34_1  conda-forge --> 1.6.0-np110py34_0 defaults       


List after `--update`:



	# packages in environment at /Users/Nick/anaconda/envs/test_env2:
	#
	click                     6.3                      py34_0    defaults
	click-plugins             1.0.3                    py34_0    ioos
	cligj                     0.2.0                    py34_0    defaults
	curl                      7.45.0                        0    defaults
	fiona                     1.6.0               np110py34_0    defaults
	gdal                      2.0.2               np110py34_1    conda-forge
	geos                      3.4.2                         1    conda-forge
	giflib                    5.1.2                         0    conda-forge
	hdf4                      4.2.11                        0    defaults
	hdf5                      1.8.15.1                      2    defaults
	jbig                      2.1                           0    defaults
	jpeg                      8d                            1    <unknown>
	kealib                    1.4.5                         0    defaults
	krb5                      1.13.2                        0    defaults
	libgcc                    4.8.5                         1    defaults
	libgdal                   2.0.0                         0    defaults
	libnetcdf                 4.3.3.1                       3    defaults
	libpng                    1.6.17                        0    <unknown>
	libtiff                   4.0.6                         1    defaults
	mkl                       11.3.1                        0    defaults
	munch                     2.0.4                    py34_0    ioos
	numpy                     1.10.4                   py34_0    defaults
	openjpeg                  2.1.0                         1    conda-forge
	openssl                   1.0.2g                        0    defaults
	pip                       8.1.1                    py34_1    defaults
	proj.4                    4.9.1                         2    conda-forge
	python                    3.4.4                         0    defaults
	readline                  6.2                           2    <unknown>
	setuptools                20.3                     py34_0    defaults
	six                       1.10.0                   py34_0    defaults
	sqlite                    3.9.2                         0    defaults
	tk                        8.5.18                        0    <unknown>
	wheel                     0.29.0                   py34_0    defaults
	xerces-c                  3.1.2                         0    defaults
	xz                        5.0.5                         1    defaults
	zlib                      1.2.8                         0    <unknown>

Sorry, feel like I'm just throwing around problems without offering solutions! Thanks again for the help.

**Comment by ocefpaf** [comment]
> Sorry, feel like I'm just throwing around problems without offering solutions! Thanks again for the help.

No problem. I am a little bit behind on some packages and I will get back to this soon.

**Comment by mhearne-usgs** [comment]
@jorisvandenbossche indicated I should post my issues with fiona here.

Mac OSX 10.10.5
conda 4.0.5

Here are the steps I used to try to install fiona from conda-forge:

conda create --name py3exp python=3 -y
source activate py3exp
conda install -y -c conda-forge fiona

and then in python:

>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mhearne/anaconda/envs/py3exp/lib/python3.5/site-packages/fiona/__init__.py", line 72, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/mhearne/anaconda/envs/py3exp/lib/python3.5/site-packages/fiona/collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/mhearne/anaconda/envs/py3exp/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: /usr/local/lib/libjson-c.2.dylib
  Referenced from: /Users/mhearne/anaconda/envs/py3exp/lib/libgdal.1.dylib
  Reason: image not found

**Comment by ocefpaf** [comment]
It looks like we also need to add `libjson` as a fiona dependency...

@jakirkham Maybe getting rid of homebrew will help is diagnose these in the CI?

**Comment by jakirkham** [comment]
Absolutely! The trick is, as you are discovering now, there may be a host of dependencies we need to add. So, we will want to role this out slowly over the feedstocks to ensure that we don't simply get swamped by missing packages and broken feedstocks.

**Comment by ocefpaf** [comment]
@nickeubank and @mhearne-usgs https://github.com/conda-forge/gdal-feedstock/pull/24 should fix these. I will bump fiona's build number as soon as the new `gdal` hits the channel.

**Comment by ocefpaf** [comment]
I bumped `fiona`'s build number (see #5) and re-compiled it against the new `gdal`. Let me know if that works for you.

**Comment by mhearne-usgs** [comment]
Fiona seems to be fixed as well by the libjson fix!  Awesome!

**Comment by ocefpaf** [comment]
Thanks for testing this out. (In fact for exposing a big problem in our workflow which was the homebrew contamination!)

**Comment by jorisvandenbossche** [comment]
You are using Anaconda / conda, so can you try installing fiona with conda instead of with pip?

> Yes, before you ask, I have all the required modules imported already...

Note, you don't need to import required modules before importing geopandas
