### ISSUE TITLE
Fiona 1.8 with gdal 2.3 ?

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/fiona-feedstock#101]
I was testing the dev packages of Fiona (https://github.com/Toblerity/Fiona/issues/647), but wondering if it would be possible to also test this with GDAL 2.3?

GDAL 2.3.2 is available on conda-forge (I can create an environment with that), but not if I also install fiona. 

Disclaimer, I don't fully understand how the pinning works on conda-forge/conda-build. But so, is the above only possible once the "global" pin of gdal is updated to 2.3? (now it is 2.2 I assume, https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/75eb2a78051dc8c6b901da1b70ffb2680dcce364/recipe/conda_build_config.yaml#L323) Unless 

Sidenote: is there actually some way to know which version of GDAL fiona is buid against / is requiring?

**Comment by ocefpaf** [comment]
> Disclaimer, I don't fully understand how the pinning works on conda-forge/conda-build.

We try to use the oldest version with the best forward compatible ABI to avoid rebuilding frequently while still allowing users to install latest version. However, all that goes down the drain when we need a "fixed" version somewhere. In the `gdal` case `fiona` is usually the package that "holds" us back.

> But so, is the above only possible once the "global" pin of gdal is updated to 2.3?

Not really. We can break pinning on a case-by-case basis if that makes sense. However, that particular package many not be installable alongside the pinned ones.

For example, `rasterio` seems OK with `gdal 2.3`, but if we built it with that `gdal` we won't be able to install it with `fiona` on the same env.


> Sidenote: is there actually some way to know which version of GDAL fiona is buid against / is requiring?

That is a question for @sgillies :grimacing: but last time I check `gdal 2.3` was not ready yet.

PS: if the dev version is OK with gdal 2.3 we definitely can break the pin and start testing.

**Comment by jorisvandenbossche** [comment]
> PS: if the dev version is OK with gdal 2.3 we definitely can break the pin and start testing.

I think it is. At least I installed it from master locally in an environment with gdal 2.3 to test some things.

> We try to use the oldest version with the best forward compatible ABI to avoid rebuilding frequently while still allowing users to install latest version.

So in principle a single fiona package would be installable in both environments with gdal 2.2 or 2.3 ?

**Comment by ocefpaf** [comment]
We have it on the dev channel now. Closing this.
