### ISSUE TITLE
Adjust for fiona's new "wheel" mark

### ISSUE THREAD

**Issue by sgillies** [conda-forge/fiona-feedstock#111]
In Fiona's maint-1.8 and master branches there are new tests that should only be run when testing wheels. They are marked and can be skipped like this: `python -m pytest -m "not wheel"`.

I feel like I probably got the mark turned inside out: it would be better if on my wheel builder I *added* tests to the suite. I'll report back here when I flip the sense of the mark around (probably this weekend).

**Comment by ocefpaf** [comment]
Thanks for the heads up!
