### ISSUE TITLE
Environment with gdal 2.3 started failing with libpoppler error

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/fiona-feedstock#135]
This might be related to the poppler error that we were discussing in https://github.com/conda-forge/fiona-feedstock/issues/134.

The env created with: https://github.com/geopandas/geopandas/blob/master/ci/travis/36-pd023.yaml started failing recently with:

```
690     import fiona
691 ../../../miniconda/envs/test/lib/python3.6/site-packages/fiona/__init__.py:83: in <module>
692     from fiona.collection import BytesCollection, Collection
693 ../../../miniconda/envs/test/lib/python3.6/site-packages/fiona/collection.py:9: in <module>
694     from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
695 E   ImportError: libpoppler.so.76: cannot open shared object file: No such file or directory
```

See eg https://travis-ci.org/geopandas/geopandas/jobs/567853381

It seems that gdal 2.3 is now coming from defaults: https://travis-ci.org/geopandas/geopandas/jobs/567853381#L568, while in the last build from a few days ago, it was still coming from conda-forge: https://travis-ci.org/geopandas/geopandas/jobs/564944938#L542

**Comment by ocefpaf** [comment]
We dropped support for `gdal 2.3` the number os dependencies required to get it working are too much for us to maintain. We are supporting 2.4.1, 2.4.2, and 3.0.1.

**Comment by jorisvandenbossche** [comment]
OK, thanks for the quick reply.

Follow-up question: "dropped support" does mean that there are no new builds made to ensure they keep working? Or were those package versions actively removed?

(I might think the second, as `conda search` does not show those any more)

**Comment by ocefpaf** [comment]
It is a mixed bag. B/c the dependencies changed and the old builds were not pinned, like ``cfitsio``, we had to remove. If that was not the case the build would not be removed.

**Comment by jorisvandenbossche** [comment]
OK, again, thanks for the explanation! 
(for CI it's not a huge problem, I can update the requirements or try to use defaults. But it seems a bit a road block for reproducibilty in case you want to re-create an environment of a couple of years ago, if using conda-forge. Now, I completely understand it is not that easy, so I am not complaining! Just a thought)

**Comment by ocefpaf** [comment]
> OK, again, thanks for the explanation!
> (for CI it's not a huge problem, I can update the requirements or try to use defaults. But it seems a bit a road block for reproducibilty in case you want to re-create an environment of a couple of years ago, if using conda-forge. Now, I completely understand it is not that easy, so I am not complaining! Just a thought)


Indeed it is not easy. However, it is not impossible either. The packages are never really remove, they are moved to the `broken` label and, if you really know what you are doing, you can still install them.

**Comment by jorisvandenbossche** [comment]
In principle (not that I am going to try it now, but as a thought experiment), if you want to ensure a certain env file keeps working, it is best to pin exactly on a set of full build numbers that was working (instead of a list of packages as I am doing in the geopandas CI)?

**Comment by ocefpaf** [comment]
> In principle (not that I am going to try it now, but as a thought experiment), if you want to ensure a certain env file keeps working, it is best to pin exactly on a set of full build numbers that was working (instead of a list of packages as I am doing in the geopandas CI)?

If the goal is full reproducibility, yes. You'll need to pin exactly to the build number and allow for channel flexibility.

IMO I do not recommend doing that with `conda`. I prefer to create a docker image with a frozen env. However, docker is not the best solution for all the platforms you may want to support.
