### ISSUE TITLE
Rebuild for GDAL 3.1

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/fiona-feedstock#164]
What exactly needs to be done to have a fiona build that can be installed with GDAL 3.1? 

Not just a rebuild I suppose? GDAL is still pinned to 3.0 in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml, but it seems there is a migration going on (https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/gdal31.yaml / https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/617, but the status page (https://conda-forge.org/status/) doesn't mention many packages that need to be rebuilt or are awaiting parents for this migration. Should fiona also be rebuilt with this migration?

**Comment by ocefpaf** [comment]
The gdal 3.1.0 migration is stuck due to an issue with conda-build on Windows.

However, it does not look like rasterio and fiona ever made into the migration. Ping @CJ-Wright and @beckermr.

**Comment by beckermr** [comment]
not sure about this. someone will need to check the graph metadata.

**Comment by theroggy** [comment]
Seems it is now stuck on 3.1? Any idea if there is something blocking to go to 3.2?

**Comment by CJ-Wright** [comment]
The PR for 3.2 is here https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/922

**Comment by weiji14** [comment]
Should there be a PR coming soon to update the `gdal` pin from 3.1 to 3.2? Just tried to install `geopandas=0.9.0` and it's trying to pull in `gdal=3.1.4` instead of the newer `gdal=3.2.1`.

**Comment by ocefpaf** [comment]
It seems that there is a bug and pkgs that depend on libgdal are not getting updates.

**Comment by weiji14** [comment]
I think this can be closed with https://github.com/conda-forge/fiona-feedstock/pull/174 merged. `conda install fiona==1.8.18` now points to GDAL 3.2 at https://anaconda.org/conda-forge/fiona/files?version=1.8.18 :smile:
