### ISSUE TITLE
Issue with build for Python 3.6 on Windows 

### ISSUE THREAD

**Issue by jGaboardi** [conda-forge/fiona-feedstock#171]
Issue:
Since last week the `fiona` build seems to be broken for Python 3.6 on Windows (see [here](https://github.com/pysal/spaghetti/runs/1250566526) for a GitHub Actions failure in pysal/spaghetti#535) for build `win-64/fiona-1.8.17-py36hdef4c2b_0.tar.bz2` and persists in `win-64/fiona-1.8.17-py36hdef4c2b_1.tar.bz2`.

<br/>
Sample traceback:
<details>

```
148 spaghetti\network.py:8: in <module>
149     from . import util
150 spaghetti\util.py:3: in <module>
151     from libpysal import cg
152 C:\Miniconda3\envs\test\lib\site-packages\libpysal\__init__.py:28: in <module>
153     from . import io
154 C:\Miniconda3\envs\test\lib\site-packages\libpysal\io\__init__.py:3: in <module>
155     from .iohandlers import *
156 C:\Miniconda3\envs\test\lib\site-packages\libpysal\io\iohandlers\__init__.py:6: in <module>
157     from . import dat
158 C:\Miniconda3\envs\test\lib\site-packages\libpysal\io\iohandlers\dat.py:2: in <module>
159.    from ...weights import W
160 C:\Miniconda3\envs\test\lib\site-packages\libpysal\weights\__init__.py:2: in <module>
161     from .distance import *
162 C:\Miniconda3\envs\test\lib\site-packages\libpysal\weights\distance.py:7: in <module>
163    from .util import isKDTree, get_ids, get_points_array_from_shapefile,\
164 C:\Miniconda3\envs\test\lib\site-packages\libpysal\weights\util.py:18: in <module>
165.   import geopandas as gpd
166 C:\Miniconda3\envs\test\lib\site-packages\geopandas\__init__.py:7: in <module>
167    from geopandas.io.file import _read_file as read_file  # noqa
168 C:\Miniconda3\envs\test\lib\site-packages\geopandas\io\file.py:7: in <module>
169    import fiona
170 C:\Miniconda3\envs\test\lib\site-packages\fiona\__init__.py:85: in <module>
171      with fiona._loading.add_gdal_dll_directories():
172 E   AttributeError: module 'fiona' has no attribute '_loading'
173 _____________________ ERROR collecting spaghetti/util.py ______________________
```

</details>

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
```
See GHA workflow output [here](https://github.com/pysal/spaghetti/runs/1250566526#step:5:1).
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
See GHA workflow output [here](https://github.com/pysal/spaghetti/runs/1250566526?check_suite_focus=true#step:4:1).
</details>

**Comment by snowman2** [comment]
I am also seeing this: AttributeError: module 'fiona' has no attribute '_loading':
https://ci.appveyor.com/project/snowman2/geocube/builds/36011148

```
fiona-1.8.17               |   py36hdef4c2b_1         954 KB  conda-forge
gdal-3.1.4                 |   py36h214b664_0         1.3 MB  conda-forge
libgdal-3.1.4              |       h0e5aa5a_0         8.8 MB  conda-forge
```

**Comment by snowman2** [comment]
Not an issue in Python 3.7. Interesting :thinking:

**Comment by jGaboardi** [comment]
> Not an issue in Python 3.7. Interesting 🤔

@snowman2 Yeah, I tested a [3x3 Python / OS matrix](https://github.com/pysal/spaghetti/pull/535#issuecomment-707791543) and only 3.6 on Windows fails.

**Comment by jGaboardi** [comment]
@ocefpaf Do you have any thoughts on this?

**Comment by ocefpaf** [comment]
Python 3.6 is lagging behind, we may need to rebuild some things for it, not sure where the problem is though.

One issue is that py36 has already reached the "scientific stack" EOL, so it will be hard to get things to build.

**Comment by jGaboardi** [comment]
> Python 3.6 is lagging behind, we may need to rebuild some things for it, not sure where the problem is though.
> 
> One issue is that py36 has already reached the "scientific stack" EOL, so it will be hard to get things to build.

Thanks for the quick reply!

**Comment by snowman2** [comment]
> One issue is that py36 has already reached the "scientific stack" EOL, so it will be hard to get things to build.

This is not a big deal if it doesn't work, for me at least. Just something I ran into.

**Comment by jGaboardi** [comment]
> > One issue is that py36 has already reached the "scientific stack" EOL, so it will be hard to get things to build.
> 
> This is not a big deal if it doesn't work, for me at least. Just something I ran into.

Also not a huge issue for me. Just wanted to make sure it wasn't something we were doing wrong in PySAL.

**Comment by jGaboardi** [comment]
This [issue](https://github.com/pysal/spaghetti/pull/551/checks?check_run_id=1414802518#step:6:542) persists with [`fiona 1.8.18`](https://github.com/pysal/spaghetti/pull/551/checks?check_run_id=1414802518#step:5:40).

**Comment by ocefpaf** [comment]
The main issue is probably our python, we need to rebuild it with the same variants we do for 3.7-3.9. The problem is to find a champion for something that is no longer supported in the scientific world (NEP 29).

**Comment by jGaboardi** [comment]
> The main issue is probably our python, we need to rebuild it with the same variants we do for 3.7-3.9. The problem is to find a champion for something that is no longer supported in the scientific world (NEP 29).

Yeah, I figured that was the issue. I just wanted to document this and I hope I didn't give you the impression I was being demanding or pushy. I am well-aware (and very appreciative) of all your contributions for the community. In [`pysal/spaghetti`](https://github.com/pysal/spaghetti/pull/552) we will be seeing about simply dropping testing for Python 3.6 on Windows.

**Comment by akrherz** [comment]
Python3.6 really isn't supported much anymore, can reopen if this is still an issue with more recent pythons
