### ISSUE TITLE
Can't build for Python 3.9 Linux-64

### ISSUE THREAD

**Issue by rwmajor2** [conda-forge/fiona-feedstock#189]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:  I am having problems building this on Linux for Python 3.9.  Can anyone offer any suggestions to help me?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by akrherz** [comment]
Please provide the output of the requested commands and how you are attempting to install fiona.
