### ISSUE TITLE
Fiona looks for libgdal.so.20 or libgdal.20.dylib, which isn't present

### ISSUE THREAD

**Issue by cmutel** [conda-forge/fiona-feedstock#19]
Fails on both OS X and linux, with:

- fiona fiona-1.7.0
- gdal 2.1.0-np111py35_6

Installed using: `conda install -c conda-forge fiona=1.7.0`

`fiona.ogrext` tries to load `libgdal.so.20` (or `libgdal.20.dylib` on OS X), but this doesn't exist. The library is `libgdal.so.2.1.0`, with symlinks from `libgdal.so.2` and `libgdal.so`. Creating another symlink from `libgdal.so.20` to `libgdal.so.2.1.0` makes everything work again.

Maybe this is an issue that crept in with recent changes to GDAL version detection?

**Comment by ocefpaf** [comment]
Thanks @cmutel I am limiting the `gdal` version to `2.1.0` to see if I can fix this.

@phobson this is the same problem you are seeing. Hopefully #17 will fix that.

**Comment by ocefpaf** [comment]
Should be fixed in #17 

Let me know if that works for you.

**Comment by cmutel** [comment]
Seems to work!
