### ISSUE TITLE
Fiona pre-release builds

### ISSUE THREAD

**Issue by sgillies** [conda-forge/fiona-feedstock#225]
### Comment:

@ocefpaf @akrherz et al: what would you think about bringing pre-release builds back to life? The last one built was before 1.8.0. The dev branch is way out of date. If it could be updated, I'd be willing to submit PRs to build Fiona 1.10 pre-releases and release candidates.

**Comment by akrherz** [comment]
Typically nobody objects when others volunteer to do work :)

**Comment by ocefpaf** [comment]
Sure. We need to follow https://github.com/conda-forge/cfep/blob/main/cfep-05.md. Note that the bot doesn't watch pre-releases. We will need to send PRs ourselves. I can create the boilerplate stuff here in this afternoon.

**Comment by xylar** [comment]
I made a go of this in #227.  It seems like there are some issues to iron out but I was able to get tests to pass (for linux-64 so far, so we'll see what happens with the rest).

**Comment by sgillies** [comment]
@xylar thanks for starting this! The reason I asked before starting is that I wasn't sure how much the process/infra had changed since the last time I added dev builds to a project.

**Comment by sgillies** [comment]
First of all, I'm super grateful for the help. Thank you @xylar !

Second: considering that the dev branch had to be completely renovated, I wonder if a workflow where dev packages are released from short-lived branches might be useful to us? I bet it's been considered, but I haven't seen any discussion.

**Comment by xylar** [comment]
I don't think most dev branches require as big a change as I had to make. There was just a lot of atrophy since last time. I think there's too high a risk of accidentally publishing to the wrong label (like recently happened with matplotlib) and releasing a package you only want to test if you make a new throw-away branch each time.

**Comment by xylar** [comment]
The biggest danger is not the source branch but the destination. If you make a new destination branch, you can accidentally publish new packages.

**Comment by sgillies** [comment]
I see 1.10b3 labeled as fiona_dev in https://anaconda.org/conda-forge/fiona/labels. Thank you very much @xylar . I'll send a PR for the first release candidate soon.
