### ISSUE TITLE
Windows 10 64-bit Environment Variable Path Issue Fiona Gdal

### ISSUE THREAD

**Issue by justinmnoor** [conda-forge/fiona-feedstock#23]
Hi I'm on Windows 10 64-bit/Anaconda3 4.1.1. I am trying to create a geospatial analysis environment in Python 2.7.12. I had some issues with the gdal environment variables.

I created my environment with 'conda create -n testenv python=2', and then 'conda install -c conda-forge fiona=1.7.0'. The installation went fine, and the following packages were installed:

![image](https://cloud.githubusercontent.com/assets/15651037/18734371/a5f45c5a-8028-11e6-84ea-00741cdd03b5.png)

I then added 'C:\Users\Justin Waltz\Anaconda3\envs\testenv\Library\bin', and 
'C:\Users\Justin Waltz\Anaconda3\envs\testenv\Library\share\gdal', to my Windows system path.

When I activated 'testenv' I got the following error:

![image](https://cloud.githubusercontent.com/assets/15651037/18734309/29bbcee8-8028-11e6-9a92-77d147f10f5a.png)

I've tried adding 'GDAL_DRIVER_PATH=C:\Users\Justin Waltz\Anaconda3\envs\testenv\Library\bin' to my environment variables because that's where the dll files are, but that did not work.

I also added 'GDAL_DATA=C:\Users\Justin Waltz\Anaconda3\envs\testenv\Library\share\gdal' to my environment variables, and that did not help.

I also tried adding 'C:\Users\Justin Waltz\Anaconda3\envs\testenv\Library\bin', and 
'C:\Users\Justin Waltz\Anaconda3\envs\testenv\Library\share\gdal', to my user path (instead of the system path) and that did not work either.

Any suggestions would be highly appreciated. Sorry if I've missed anything in the installation instructions.

Thank you.

**Comment by ocefpaf** [comment]
Did you try not adding anything to the path? Conda-env should do that for you. Please try that in a clean env and let me know if it works.

**Comment by justinmnoor** [comment]
Yes I tried that. As an extra precaution I also did a fresh install of Anaconda3 4.1.1, and then I reinstalled Fiona with 'conda install -c conda-forge fiona=1.7.0', and then created a clean environment with 'conda create -n testenv python=2'.

At first the 'set GDAL_DRIVER_PATH=' part of the message disappeared, but when I restarted my computer the message came back.

![image](https://cloud.githubusercontent.com/assets/15651037/18748019/44eaef02-8085-11e6-80d9-23412889037d.png)

Thanks

**Comment by justinmnoor** [comment]
Sorry I accidentally closed the issue. That was a mistake. I reopened it.

**Comment by ocefpaf** [comment]
I do not have a Windows machine to test that. Hopefully someone with a Windows setup can help you. However, I am closing this here b/c it is related to `gdal` and not `fiona`. Please open an issue in the gdal feedstock (and hopefully someone with Windows will see it).
