### ISSUE TITLE
import fiona failes on Mac OS 10.12

### ISSUE THREAD

**Issue by tckramer** [conda-forge/fiona-feedstock#26]
There appears to be a out of date dependency in the fiona feedstock.

After Running:

```shell
conda create -n test-fiona
source activate test-fiona
conda install fiona -c conda-forge

from ipython:
In [1]: import fiona
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-cc872b235141> in <module>()
----> 1 import fiona

/opt/python/anaconda/lib/python2.7/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

/opt/python/anaconda/lib/python2.7/site-packages/fiona/collection.py in <module>()
      5 import sys
      6 
----> 7 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
      8 from fiona.ogrext import Session, WritingSession
      9 from fiona.ogrext import (

ImportError: dlopen(/opt/python/anaconda/lib/python2.7/site-packages/fiona/ogrext.so, 2): Library not loaded: @rpath/libgdal.20.dylib
  Referenced from: /opt/python/anaconda/lib/python2.7/site-packages/fiona/ogrext.so
  Reason: Incompatible library version: ogrext.so requires version 22.0.0 or later, but libgdal.20.dylib provides version 21.0.0
```

**Comment by ocefpaf** [comment]
Can you send the results from `conda info` and `conda list`? You many be getting into a bad mix of channels there. This should work BTW:

```shell
conda update conda --yes  # To ensure you have latest conda with the channel preference feature.
conda create -n TEST -c conda-forge fiona --yes  # Create the env and install `fiona` in one go so `conda-forge` there is used as the preferred channel.
source activate TEST
python -c "import fiona; print(fiona.__version__)"
1.7.0.post2
```

**Comment by tckramer** [comment]
Hi, thanks for the response.  

`
(test-fiona) Tylers-MBP:magpy-demos tyler$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 1.18.1
         python version : 2.7.11.final.0
       requests version : 2.9.1
       root environment : /opt/python/anaconda  (writable)
    default environment : /opt/python/anaconda/envs/test-fiona
       envs directories : /opt/python/anaconda/envs
          package cache : /opt/python/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
`
and
`
(test-fiona) Tylers-MBP:magpy-demos tyler$ conda list
# packages in environment at /opt/python/anaconda/envs/test-fiona:
#
ca-certificates           2016.9.26                     0    conda-forge
certifi                   2016.9.26                py27_0    conda-forge
click                     6.6                      py27_1    conda-forge
click-plugins             1.0.3                    py27_0    conda-forge
cligj                     0.4.0                    py27_0  
curl                      7.49.1                        1    conda-forge
expat                     2.1.0                         2    conda-forge
fiona                     1.7.0               np111py27_3    conda-forge
freexl                    1.0.2                         1    conda-forge
gdal                      2.1.2               np111py27_1    conda-forge
geos                      3.4.2                         2    conda-forge
giflib                    5.1.4                         0    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.17                        7    conda-forge
icu                       56.1                          4    conda-forge
jpeg                      9b                            0    conda-forge
json-c                    0.12                          0    conda-forge
kealib                    1.4.6                         3    conda-forge
libdap4                   3.18.2                        0    conda-forge
libgfortran               3.0.0                         0    conda-forge
libiconv                  1.14                          3    conda-forge
libnetcdf                 4.4.1                         0    conda-forge
libpng                    1.6.26                        0    conda-forge
libpq                     9.5.4                         3    conda-forge
libspatialite             4.3.0a                       11    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxml2                   2.9.4                         3    conda-forge
mkl                       11.3.3                        0  
munch                     2.0.4                    py27_0    conda-forge
ncurses                   5.9                           9    conda-forge
numpy                     1.11.2                   py27_0  
openjpeg                  2.1.2                         1    conda-forge
openssl                   1.0.2h                        2    conda-forge
pip                       9.0.1                    py27_0    conda-forge
proj4                     4.9.3                         0    conda-forge
python                    2.7.12                        1    conda-forge
readline                  6.2                           0    conda-forge
setuptools                28.8.0                   py27_0    conda-forge
six                       1.10.0                   py27_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        0    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
xerces-c                  3.1.4                         2    conda-forge
xz                        5.2.2                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
`
After running your other commands, I think I found my problem.  I was running ipython which I hadn't installed in my virtual python env to test whether or not I could import fiona.  When I started ipython from the command line, it must have been using the global/root version.  Adding ipython to the env appears to fix the issue.

Thanks so much for your help.

**Comment by ocefpaf** [comment]
Awesome. I can see that you indeed got the right `gdal` in there:

`gdal                      2.1.2               np111py27_1    conda-forge`
