### ISSUE TITLE
Can't locate gdal on macOS

### ISSUE THREAD

**Issue by fonnesbeck** [conda-forge/fiona-feedstock#31]
I get an import error when loading fiona following a successful install from conda-forge. Apparently it is looking for a library from icu4c, but I have ensured this is installed (via homebrew).

Running Python 3.5 (Anaconda) on macOS 10.12.

```
In [2]: import fiona
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-cc872b235141> in <module>()
----> 1 import fiona

/Users/fonnescj/anaconda3/envs/gbs/lib/python3.5/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

/Users/fonnescj/anaconda3/envs/gbs/lib/python3.5/site-packages/fiona/collection.py in <module>()
      6 
      7 from fiona import compat
----> 8 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
      9 from fiona.ogrext import Session, WritingSession
     10 from fiona.ogrext import (

ImportError: dlopen(/Users/fonnescj/anaconda3/envs/gbs/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libicui18n.56.dylib
  Referenced from: /Users/fonnescj/anaconda3/envs/gbs/lib/libgdal.20.dylib
  Reason: image not found
```

**Comment by ocefpaf** [comment]
Did you installed `fiona` in an isolated env or at the root env? Can you send the `conda info` and `conda list` results?

**Comment by ResidentMario** [comment]
The same issue occurs for me on Ubuntu 16.x. Here's the code path (with `conda-forge` appended to the channels list):

```
conda create --name failtest cartopy geopandas
source activate failtest
python -c "import fiona"
```

This raises:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alex/anaconda3/envs/failtest5/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/alex/anaconda3/envs/failtest5/lib/python3.5/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libmfhdf.so.0: cannot open shared object file: No such file or directory

```

As a consequence, it appears to me that `cartopy` and `geopandas` can be simul-installed on Ubuntu. Perhaps this is a recent change; this same sequence of actions worked for me a month ago.

**Comment by ocefpaf** [comment]
That is not gdal. It is a missing  (or wrong version) of a build
dependency. Looks like a bad mix of packages from defaults and conda-forge.
Do you have channel preference enabled? (That is default in newer conda.)
How is your .condarc file?

**Comment by ResidentMario** [comment]
Here's my `.condarc`:

```
channels:
  - defaults
  - conda-forge
```
I installed this Anaconda distribution two days ago, so yes (though, not being sure what that means, I don't know how to check this for sure).

**Comment by ocefpaf** [comment]
That is probably the problem. Try putting conda-forge on top of defaults
and conda will 'prefer' conda-forge packages. That should get gdal's
dependencies correctly.

**Comment by ResidentMario** [comment]
That resolves it. Interesting, will know this for the future.

**Comment by ocefpaf** [comment]
@ResidentMario please take a look at: https://github.com/conda-forge/conda-forge.github.io/pull/325

I am trying to create some docs to explain this. Your input there is welcomed!

**Comment by ResidentMario** [comment]
Ok, I will take a look, but from the perspective of an end user.

FWIW I was vaguely aware of the issue that I ran into here only because I leafed through the conda-forge tutorial docs one time, but I wasn't aware that the *default* channel was included in potential incompatibility surfaces.

So a Gotcha page like the one you're writing does indeed seem necessary.
