### ISSUE TITLE
Conda install fails

### ISSUE THREAD

**Issue by darribas** [conda-forge/fiona-feedstock#54]
Hello,

Not sure if this is the adequate channel for this question; if not please let me know. I'm trying to set up the following conda environment:

```yml
# file name: install_stack.yml
name: mlm
channels:
  - conda-forge
  - bokeh
  - r
dependencies:
  - python=3.5
  - pip
  - bokeh
  - cartopy
  - dask
  - geopandas
  - ipython
  - ipywidgets
  - jupyter
  - mkl-service
  - networkx
  - palettable
  - pillow
  - pip:
        - contextily
        - pystan
        - bambi
  - pymc3
  - pysal
  - rasterio
  - scikit-learn
  - seaborn
  - statsmodels
  - xlrd
  - xlsxwriter
  # R
  - r
  - r-lme4
```

When I run `conda-env create -f install_stack.yml` on macOS Sierra (10.12.6), and activate, I obtain the following:

```shell
(mlm) dh073213:Desktop dani$ python -c "import geopandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dani/anaconda/envs/mlm/lib/python3.5/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/Users/dani/anaconda/envs/mlm/lib/python3.5/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/Users/dani/anaconda/envs/mlm/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/dani/anaconda/envs/mlm/lib/python3.5/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/dani/anaconda/envs/mlm/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libkea.1.4.7.dylib
  Referenced from: /Users/dani/anaconda/envs/mlm/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 1.4.7 or later, but libkea.1.4.7.dylib provides version 1.4.0
(mlm) dh073213:Desktop dani$
```

Any idea on why it happens and how to fix it? @ocefpaf maybe?

Thank you very much in advance!

]d[

**Comment by ocefpaf** [comment]
Can you post the results of `conda list` for that env? I am guessing that the 3 extra channels are pulling incompatible versions of `libgdal` and `libkea`.

BTW, do you need `bokeh` and `r`? I am not sure what is provided in the former but if it is only `bokeh` you can get that from both `defaults` and `conda-forge`. The latter was merged in `defaults` too. Not sure of the `r` channel is still supported.

**Comment by ocefpaf** [comment]
I just tried:

```yaml
name: mlm
channels:
  - conda-forge
dependencies:
  - python=3.5
  - pip
  - bokeh
  - cartopy
  - dask
  - geopandas
  - ipython
  - ipywidgets
  - jupyter
  - mkl-service
  - networkx
  - palettable
  - pillow
  - pip:
    - contextily
    - pystan
    - bambi
  - pymc3
  - pysal
  - rasterio
  - scikit-learn
  - seaborn
  - statsmodels
  - xlrd
  - xlsxwriter
  # R
  - r
  - r-lme4
```

and everything worked for me.

**Comment by darribas** [comment]
Thank you very much @ocefpaf for contributing. I didn't know most of R was in the `defaults`/`conda-forge` and it's a great suggestion to try to simplify the channel list. I've just tried the `.yml` you suggest and, although it runs, when I try to import `geopandas`, I obtain a similar error:

```python
In [1]: import geopandas
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-fc7d1d298f0c> in <module>()
----> 1 import geopandas

~/anaconda/envs/mlm/lib/python3.5/site-packages/geopandas/__init__.py in <module>()
      2 from geopandas.geodataframe import GeoDataFrame
      3 
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

~/anaconda/envs/mlm/lib/python3.5/site-packages/geopandas/io/file.py in <module>()
      1 import os
      2 
----> 3 import fiona
      4 import numpy as np
      5 

~/anaconda/envs/mlm/lib/python3.5/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

~/anaconda/envs/mlm/lib/python3.5/site-packages/fiona/collection.py in <module>()
      7 
      8 from fiona import compat
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import (

ImportError: dlopen(/Users/dani/anaconda/envs/mlm/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libkea.1.4.7.dylib
  Referenced from: /Users/dani/anaconda/envs/mlm/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 1.4.7 or later, but libkea.1.4.7.dylib provides version 1.4.0

In [2]:
```

This is on Mac, same as before. I'll keep trying to see if I find a combination that seems to work. Do you know what `libkea` relates to or what libraries might import it by any chance?

**Comment by ocefpaf** [comment]
I guess that it is related to a new change in `libkea` (a `gdal` dependency). See https://github.com/conda-forge/rsgislib-feedstock/pull/5#issuecomment-335767383

Hopefully https://github.com/conda-forge/libgdal-feedstock/pull/11 will fix it.

**Comment by darribas** [comment]
I've tried it in a couple of macs and keeps giving the same problem w/ `kealib`. Will keep investigating...

**Comment by ocefpaf** [comment]
You'll probably need to wait for conda-forge/libgdal-feedstock#11 to be merged.

**Comment by darribas** [comment]
Thanks very much @ocefpaf!!! I've tried it on a Linux box and it seems to work so I'm going to give docker a try to get going for now. But I'll keep an eye on this to see if then it works properly natively on a Mac. Thank you very much!

**Comment by ocefpaf** [comment]
@darribas you can try again as soon as https://travis-ci.org/conda-forge/libgdal-feedstock/builds/286622650 finishes.

**Comment by darribas** [comment]
Excellent! I'll report back! Just in case, here's a docker file I've created as a work around:

https://github.com/darribas/mlm

**Comment by darribas** [comment]
Mmm... this is what I get:

```shell
liverbird:Desktop dani$ conda-env create -f install_stack.yml 
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - rasterio
Use "conda info <package>" to see the dependencies for each package.

liverbird:Desktop dani$
```

**Comment by darribas** [comment]
That's using [this install file](https://github.com/darribas/mlm/blob/master/env.yml)

**Comment by ocefpaf** [comment]
I had to pull the `libgdal` that was linked to the bad `kealib` the new one will be ready soon. (Travis-CI is quite slow these days :unamused:)

**Comment by darribas** [comment]
Cool, no worries, just ping when you want me to give it a spin!

**Comment by ocefpaf** [comment]
Things should be back to normal now. I'm closing this but please re-open if you still see failures.

**Comment by darribas** [comment]
Finally had a chance to give this a spin and seems to work without problem! Thanks very much @ocefpaf!!!

**Comment by ocefpaf** [comment]
Awesome!
