### ISSUE TITLE
ImportError: undefined symbol

### ISSUE THREAD

**Issue by janfreyberg** [conda-forge/fiona-feedstock#61]
Hi all,

I just tried to install fiona from conda-forge and am getting an ImportError that seems like it's a bug.

## What I wanted to do

Import fiona

## What happened

On import, the following happens:

```
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: /opt/anaconda/envs/Python3/lib/python3.6/site-packages/fiona/../../.././libkea.so.1.4: undefined symbol: _ZN2H56H5FileC1ERKSsjRKNS_17FileCreatPropListERKNS_15FileAccPropListE
```

My environment:

`64-bit Ubuntu`, `python Python 3.6.2`, `anaconda 64-bit`

Fiona version & conda-forge channel:

`fiona                     1.7.10                   py36_2    conda-forge`

Conda configuration:
```
$ cat .condarc
channels:
  - conda-forge
  - defaults
```

---

Any advice? It seems to work fine with the same python version on OS X, so I'm not 100% sure what's wrong.

**Comment by ocefpaf** [comment]
Having `conda-forge` on top of `defaults` does not help much lately b/c conda is breaking the channel preference, specially when you are using the anaconda distribution that brings tons of packages pre-installed. See https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels for the recommended way to install in an environment.

I just tested,

```shell
conda create --yes -n TEST_fiona python=3.6 fiona 
source activate TEST_fiona
python -c "import fiona; print(fiona.__version__)" 
```

and everything worked.
