### ISSUE TITLE
gdal incompatibility

### ISSUE THREAD

**Issue by fonnesbeck** [conda-forge/fiona-feedstock#64]
Having installed fiona via conda on macOS and Python 3.6, I get a library incompatibility with libgdal. 

```
ImportError: dlopen(/Users/fonnescj/anaconda3/envs/dev/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libiconv.2.dylib
  Referenced from: /Users/fonnescj/anaconda3/envs/dev/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 9.0.0 or later, but libiconv.2.dylib provides version 8.0.0
```
After reading some troubleshooting on this online, I've also tried the following:

```
 conda create -n gis -c conda-forge --override-channels python=3.5 gdal=2.1.0
```

But I get the same error. Any workarounds for this?

**Comment by ocefpaf** [comment]
I need more details on how you created your first environment. The second commend won't work b/c `gdal 2.1.0` is too old. Latest `fiona` would use `2.1.4` or `2.1.3` depending on the dependencies but you should not specify that explicitly, let conda choose it for you.

**Comment by fonnesbeck** [comment]
Thanks. Letting conda decide things seems to have done the trick.
