### ISSUE TITLE
Fiona after clean install from condo-forge

### ISSUE THREAD

**Issue by timothybeatty** [conda-forge/fiona-feedstock#65]
As best I can tell (which is probably not very well), Fiona installed from condo-forge breaks for me.  If I execute the following steps:

```
conda create -n pygis
source activate pygis
conda install -c conda-forge fiona shapely pyproj rtree
conda install pandas
jupyter-console
import fiona as fi
```

I get following error message:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-8ec341eff55d> in <module>()
----> 1 import fiona as fi

~/anaconda3/lib/python3.6/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

~/anaconda3/lib/python3.6/site-packages/fiona/collection.py in <module>()
      7 
      8 from fiona import compat
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import (

ImportError: /home/XXXXXX/anaconda3/lib/python3.6/site-packages/fiona/../../.././libkea.so.1.4.7: undefined symbol: _ZN2H56H5FileC1ERKSsjRKNS_17FileCreatPropListERKNS_15FileAccPropListE'
ImportError                               Traceback (most recent call last)
<ipython-input-1-8ec341eff55d> in <module>()
----> 1 import fiona as fi

~/anaconda3/lib/python3.6/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

~/anaconda3/lib/python3.6/site-packages/fiona/collection.py in <module>()
      7 
      8 from fiona import compat
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import (

ImportError: /home/XXXXXXX/anaconda3/lib/python3.6/site-packages/fiona/../../.././libkea.so.1.4.7: undefined symbol: _ZN2H56H5FileC1ERKSsjRKNS_17FileCreatPropListERKNS_15FileAccPropListE'
```

I'm probably doing something wrong, but I'm not sure what.  Any help would be appreciated.

**Comment by Victornovikov** [comment]
same issue
I do (under py27 environment, py3 seems to work fine?)
> conda install -c conda-forge geopandas

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-b1c816a85bae> in <module>()
      3 from StringIO import StringIO
      4 import shapefile
----> 5 import geopandas as gpd
      6 from shapely.geometry import shape
      7 import osr

/home/XXX/miniconda3/envs/py27/lib/python2.7/site-packages/geopandas/__init__.pyc in <module>()
      2 from geopandas.geodataframe import GeoDataFrame
      3 
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

/home/XXXX/miniconda3/envs/py27/lib/python2.7/site-packages/geopandas/io/file.py in <module>()
      1 import os
      2 
----> 3 import fiona
      4 import numpy as np
      5 

/home/XXX/miniconda3/envs/py27/lib/python2.7/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

/home/XXX/miniconda3/envs/py27/lib/python2.7/site-packages/fiona/collection.py in <module>()
      7 
      8 from fiona import compat
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import (

ImportError: /home/XXXXX/miniconda3/envs/py27/lib/python2.7/site-packages/fiona/../../.././libkea.so.1.4.7: undefined symbol: _ZN2H56H5FileC1ERKSsjRKNS_17FileCreatPropListERKNS_15FileAccPropListE
```

**Comment by Victornovikov** [comment]
So i tried to do a clean install
`
>  conda create -n geotest27 python=2.7 anaconda
>  conda install -c conda-forge geopandas  
`
Now I am getting -- 

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-cca12e125034> in <module>()
      3 from StringIO import StringIO
      4 # import shapefile
----> 5 import geopandas as gpd
      6 from shapely.geometry import shape
      7 import osr

/home/vicnov/miniconda3/envs/geotest27/lib/python2.7/site-packages/geopandas/__init__.pyc in <module>()
      2 from geopandas.geodataframe import GeoDataFrame
      3 
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

/home/vicnov/miniconda3/envs/geotest27/lib/python2.7/site-packages/geopandas/io/file.py in <module>()
      1 import os
      2 
----> 3 import fiona
      4 import numpy as np
      5 

/home/vicnov/miniconda3/envs/geotest27/lib/python2.7/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

/home/vicnov/miniconda3/envs/geotest27/lib/python2.7/site-packages/fiona/collection.py in <module>()
      5 import sys
      6 
----> 7 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
      8 from fiona.ogrext import Session, WritingSession
      9 from fiona.ogrext import (

ImportError: libgeos-3.4.2.so: cannot open shared object file: No such file or directory`
--------
Also ... not sure it is helpful, but just in case.
I tried installing fiona and geopandas form pip.. that gave me a new error now in gdal (not sure if it is related.)
`
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-b1c816a85bae> in <module>()
      5 import geopandas as gpd
      6 from shapely.geometry import shape
----> 7 import osr
      8 import pandas as pd
      9 import requests

....... 

swig_import_helper()
     15         if fp is not None:
     16             try:
---> 17                 _mod = imp.load_module('_gdal', fp, pathname, description)
     18             finally:
     19                 fp.close()

ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory

`

**Comment by ocefpaf** [comment]
> conda create -n geotest27 python=2.7 anaconda
> conda install -c conda-forge geopandas

@Victornovikov you cannot mix anaconda packages and conda-forge. Please see https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

@timothybeatty your problem is probably similar but I cannot tell without looking at your `.condarc`, you can check the origin of your package with `conda list` inside that env and, if you have packages from `defaults`, you have the same issue.

Please try to install everything in a clean env by following the instruction from the link above.
