### ISSUE TITLE
dependencies of 1.7.11 force multiple downgrades

### ISSUE THREAD

**Issue by michaelaye** [conda-forge/fiona-feedstock#69]
Trying to upgrade to 1.7.11 currently forces a whole bunch of, I believe, unnecessary downgrades:

```bash
(stable) └─❱❱❱ conda update fiona                                                      +9025 18:15 ❰─┘
Solving environment: done

## Package Plan ##

  environment location: /Users/klay6683/miniconda3/envs/stable

  added / updated specs:
    - fiona


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fiona-1.7.11               |           py36_1         622 KB  conda-forge
    cairo-1.14.6               |                4         1.2 MB  conda-forge
    fontconfig-2.12.1          |                4         266 KB  conda-forge
    glib-2.51.4                |                0         4.9 MB  conda-forge
    pillow-4.2.1               |           py36_0         504 KB  conda-forge
    gdal-2.1.4                 |           py36_2         643 KB  conda-forge
    matplotlib-2.1.0           |           py36_0         6.6 MB  conda-forge
    openjpeg-2.1.2             |                2         222 KB  conda-forge
    freetype-2.7               |                1         771 KB  conda-forge
    poppler-0.52.0             |                2         1.4 MB  conda-forge
    libgdal-2.1.4              |                9        12.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        29.9 MB

The following packages will be UPDATED:

    fiona:      1.7.10-py36h42caba7_0             --> 1.7.11-py36_1 conda-forge

The following packages will be DOWNGRADED:

    cairo:      1.14.10-0             conda-forge --> 1.14.6-4      conda-forge
    fontconfig: 2.12.6-0              conda-forge --> 2.12.1-4      conda-forge
    freetype:   2.8.1-0               conda-forge --> 2.7-1         conda-forge
    gdal:       2.2.3-py36_0          conda-forge --> 2.1.4-py36_2  conda-forge
    glib:       2.55.0-0              conda-forge --> 2.51.4-0      conda-forge
    libgdal:    2.2.3-2               conda-forge --> 2.1.4-9       conda-forge
    matplotlib: 2.1.2-py36_0          conda-forge --> 2.1.0-py36_0  conda-forge
    openjpeg:   2.3.0-2               conda-forge --> 2.1.2-2       conda-forge
    pillow:     5.0.0-py36_0          conda-forge --> 4.2.1-py36_0  conda-forge
    poppler:    0.61.1-3              conda-forge --> 0.52.0-2      conda-forge

Proceed ([y]/n)? n
```

System: macOS 10.12.6

**Comment by ocefpaf** [comment]
> Trying to upgrade to 1.7.11 currently forces a whole bunch of, I believe, unnecessary downgrades:

Nope. Those are necessary b/c conda-forge's `fiona` is built against `gdal 2.1.4` and that cause the downgrades. Your starting point is `fiona` from `defaults`, which has a patch to work with `gdal 2.2.3`. We do not apply that patch.

**Comment by michaelaye** [comment]
Understood, sorry for the noise, I don't know why I even came from a defaults fiona, must have been when I was fiddling with the conda update. 
I see that you are also maintaining the gdal feedstock? May I ask why matplotlib needs to be tied specifically? Is there a library used of it inside gdal?

**Comment by ocefpaf** [comment]
> May I ask why matplotlib needs to be tied specifically? Is there a library used of it inside gdal?

It is not `matplotlib` but their common dependencies, like `freetype` and `fontconfig`. As long as `fiona` is not build against `gdal 2.2.*` many other packages will be downgraded b/c of that.

**Comment by michaelaye** [comment]
Aha, now I see how I got that defaults fiona: It came with geopandas conda-forge, that for some reason ties to the defaults fiona.

**Comment by ocefpaf** [comment]
The `conda` solver is a little wonky and does not really respect channel preference :unamused: 

Unfortunately this situation will only get better when conda-forge moves to conda-build 3.

PS: the next version of `fiona` should be compatible with `gdal 2.2.*`.

**Comment by michaelaye** [comment]
Wonky indeed: I just created a new env  for the purpose of not having geopandas rule my other libraries, using this:
```bash
conda create -n geopandas python=3 geopandas --file standard_packages.txt
```
and suddenly, matplotlib 2.1.2 is **NOT** a problem for being matched with default's fiona?

**Comment by akrherz** [comment]
Sorry to chime in on this closed issue, but I am struggling to resolve how to fix this situation.  Currently, my conda-forge env seems very fragile (conda update will loop infinitely with upgrades and downgrades each time I run it) due to this fiona + GDAL issue.  What's the suggested workaround?  Install fiona from the default channel and then prevent the newer version in conda-forge from updating it?  Is there some issue from having this patched fiona from defaults coming into conda-forge?

**Comment by michaelaye** [comment]
Because I don't need fiona (and the bound geopandas) everyday, I just made a new env with fiona and removed it from my everyday env.
I use GDAL everyday, so I did not want to downgrade GDAL for my everyday work, but YMMV.

**Comment by ocefpaf** [comment]
> Sorry to chime in on this closed issue, but I am struggling to resolve how to fix this situation.

Closed issue do not necessarily mean that the issue is solved and/or we should not talk about it :smile: 
(Just that we cannot act on it now.)

>  Currently, my conda-forge env seems very fragile (conda update will loop infinitely with upgrades and downgrades each time I run it) due to this fiona + GDAL issue. 

Sorry about that. It will get better when we move to conda-build 3 and/or `fiona 1.8` is released.

> What's the suggested workaround? 

Creating envs in "one go" usually works without a problem. Updating packages and/or installing packages after an env is created usually bring those problems.

> Install fiona from the default channel and then prevent the newer version in conda-forge from updating it?

That is one option.

> Is there some issue from having this patched fiona from defaults coming into conda-forge?

Just human hours. No one volunteered to patch the `fiona` in `conda-forge`. Also, we hope that latest `fiona` with proper `gdal 2.2` support will be released soon.

**Comment by akrherz** [comment]
> Just human hours. No one volunteered to patch the fiona in conda-forge. Also, we hope that latest fiona with proper gdal 2.2 support will be released soon.

I'm not too optimistic on the timing of the next release of fiona given Sean's current travels, etc.  Is all that's needed here is to work [this patch](https://github.com/AnacondaRecipes/fiona-feedstock/commit/899952cb770f8d63c0ef61123604710e7cf89b90) into conda-forge? Thank you

**Comment by ocefpaf** [comment]
> Is all that's needed here is to work this patch into conda-forge?

Not sure. Do you fancy a PR to try it?
