### ISSUE TITLE
Cannot import fiona on Mac

### ISSUE THREAD

**Issue by mhearne-usgs** [conda-forge/fiona-feedstock#78]
Platform: OSX 10.12.6 (Sierra)
conda version:  4.5.4

Given the attached environment yml (uploaded as .txt) file, I run the following commands:
conda deactivate
conda remove -n mytest --all -y
conda env create -f environment.yml
conda activate mytest
python -c "import fiona"

Resulting in the following set of errors:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mhearne/miniconda3/envs/mytest/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/mhearne/miniconda3/envs/mytest/lib/python3.5/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/mhearne/miniconda3/envs/mytest/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libjson-c.2.dylib
  Referenced from: /Users/mhearne/miniconda3/envs/mytest/lib/libgdal.20.dylib
  Reason: image not found

[environment.txt](https://github.com/conda-forge/fiona-feedstock/files/2074060/environment.txt)

**Comment by ocefpaf** [comment]
Can you send the results of `conda list` from that env? But my guess is that the `matplotlib<2.0` is a problem. We can ensure that an old build will work there. Maybe we should build a new `matplotlib 1.*`.

**Comment by mhearne-usgs** [comment]
See attached.
[myenv_list.txt](https://github.com/conda-forge/fiona-feedstock/files/2076746/myenv_list.txt)

**Comment by ocefpaf** [comment]
As I suspected there are tons of old packages with inconsistent pins there due to the old `matplotlib` :-(

https://github.com/conda-forge/matplotlib-feedstock/pull/159 should fix that.

**Comment by mhearne-usgs** [comment]
Ok, I don't get how old packages break the version of fiona that I'm trying to use.  Regardless, I'll try modifying my matplotlib version range and see what happens.

**Comment by ocefpaf** [comment]
@mhearne-usgs can you try that again? It should be fixed now.

**Comment by mhearne-usgs** [comment]
Whatever reason I had for needing older versions of matplotlib are gone, so I've updated my package to use newer versions.  I'm having similar issues with another environment file and libgdal, so I'll ping you once I narrow down that problem. Thanks for your help!
