### ISSUE TITLE
Cannot import Fiona to Jupyter notebook

### ISSUE THREAD

**Issue by yutingwum** [conda-forge/fiona-feedstock#79]
Hi I installed GeoPandas and Fiona but cannot import to Jupyter Notebook. 
![wx20180607-1500022x](https://user-images.githubusercontent.com/23270584/41120692-4b0220e8-6a64-11e8-9970-6a9106d7e10e.png)

![image](https://user-images.githubusercontent.com/23270584/41120712-5ced70c8-6a64-11e8-8ae1-bbbc1ad238f7.png)

part of my package list. I am sure i have all the dependency fiona and geopands require. But I just cannot import Fiona and hence cannot import GeoPandas.

Any help is appreciated!

**Comment by ocefpaf** [comment]
Same as https://github.com/conda-forge/geopandas-feedstock/issues/38
