### ISSUE TITLE
Cannot import fiona via geopandas

### ISSUE THREAD

**Issue by rgommers** [conda-forge/fiona-feedstock#83]
Stole the title from gh-82, this seems different though (the GDAL/hdf5 issue was just resolved). Seeing this on 64-bit Linux, Python 3.6.

```
$ conda create -n test-gdp
...
$ conda activate test-gdp
(test-gdp) $ conda install geopandas
Solving environment: done

## Package Plan ##

  environment location: /home/rgommers/anaconda3/envs/test-gdp

  added / updated specs: 
    - geopandas


The following NEW packages will be INSTALLED:

    ca-certificates:  2018.4.16-0           conda-forge
    certifi:          2018.4.16-py36_0      conda-forge
    click:            6.7-py_1              conda-forge
    click-plugins:    1.0.3-py36_0          conda-forge
    cligj:            0.4.0-py36_0          conda-forge
    curl:             7.60.0-0              conda-forge
    cycler:           0.10.0-py36_0         conda-forge
    dbus:             1.13.0-h3a4f0e9_0     conda-forge
    descartes:        1.1.0-py_1            conda-forge
    expat:            2.2.5-hfc679d8_1      conda-forge
    fiona:            1.7.9-py36_0          conda-forge
    fontconfig:       2.12.6-0              conda-forge
    freetype:         2.8.1-0               conda-forge
    freexl:           1.0.5-hf837533_1      conda-forge
    geopandas:        0.3.0-py36_0          conda-forge
    geos:             3.6.2-hfc679d8_2      conda-forge
    geotiff:          1.4.2-hb54a4aa_2      conda-forge
    gettext:          0.19.8.1-0            conda-forge
    giflib:           5.1.4-h470a237_0      conda-forge
    glib:             2.55.0-0              conda-forge
    gst-plugins-base: 1.8.0-0               conda-forge
    gstreamer:        1.8.0-1               conda-forge
    hdf4:             4.2.13-0              conda-forge
    hdf5:             1.10.1-2              conda-forge
    icu:              58.2-hfc679d8_0       conda-forge
    intel-openmp:     2018.0.3-0                       
    jpeg:             9c-h470a237_0         conda-forge
    json-c:           0.13.1-h470a237_0     conda-forge
    kealib:           1.4.7-4               conda-forge
    kiwisolver:       1.0.1-py36_1          conda-forge
    krb5:             1.14.6-0              conda-forge
    libdap4:          3.18.3-2              conda-forge
    libffi:           3.2.1-3               conda-forge
    libgcc:           7.2.0-h69d50b8_2                 
    libgcc-ng:        7.2.0-hdf63c60_3                 
    libgdal:          2.1.4-9               conda-forge
    libgfortran:      3.0.0-1                          
    libgfortran-ng:   7.2.0-hdf63c60_3                 
    libiconv:         1.15-h470a237_1       conda-forge
    libnetcdf:        4.4.1.1-10            conda-forge
    libpng:           1.6.34-ha92aebf_1     conda-forge
    libpq:            9.6.3-0               conda-forge
    libspatialindex:  1.8.5-hfc679d8_2      conda-forge
    libspatialite:    4.3.0a-19             conda-forge
    libssh2:          1.8.0-h5b517e9_2      conda-forge
    libstdcxx-ng:     7.2.0-hdf63c60_3                 
    libtiff:          4.0.9-he6b73bb_1      conda-forge
    libxcb:           1.13-h470a237_0       conda-forge
    libxml2:          2.9.8-h422b904_1      conda-forge
    matplotlib:       2.2.2-py36_1          conda-forge
    mkl:              2018.0.3-1                       
    mkl_fft:          1.0.2-py36_0          conda-forge
    mkl_random:       1.0.1-py36_0          conda-forge
    munch:            2.3.2-py_0            conda-forge
    ncurses:          5.9-10                conda-forge
    numpy:            1.14.2-py36hdbf6ddf_1            
    openjpeg:         2.3.0-h0e734dc_3      conda-forge
    openssl:          1.0.2o-0              conda-forge
    pandas:           0.23.1-py36_0         conda-forge
    pcre:             8.39-0                conda-forge
    pip:              9.0.3-py36_0          conda-forge
    proj4:            4.9.3-5               conda-forge
    psycopg2:         2.7.5-py36_0          conda-forge
    pyparsing:        2.2.0-py36_0          conda-forge
    pyproj:           1.9.5.1-py36_0        conda-forge
    pyqt:             5.6.0-py36_5          conda-forge
    pysal:            1.14.3-py36_0         conda-forge
    python:           3.6.5-1               conda-forge
    python-dateutil:  2.7.3-py_0            conda-forge
    pytz:             2018.5-py_0           conda-forge
    qt:               5.6.2-7               conda-forge
    readline:         7.0-0                 conda-forge
    rtree:            0.8.3-py36_0          conda-forge
    scipy:            1.1.0-py36hfc37229_0             
    setuptools:       39.2.0-py36_0         conda-forge
    shapely:          1.6.4-py36h164cb2d_1  conda-forge
    sip:              4.18-py36_1           conda-forge
    six:              1.11.0-py36_1         conda-forge
    sqlalchemy:       1.2.9-py36_0          conda-forge
    sqlite:           3.20.1-2              conda-forge
    tk:               8.6.7-0               conda-forge
    tornado:          5.0.2-py36_0          conda-forge
    util-linux:       2.21-0                           
    wheel:            0.31.0-py36_0         conda-forge
    xerces-c:         3.2.0-0               conda-forge
    xorg-libxau:      1.0.8-3               conda-forge
    xorg-libxdmcp:    1.1.2-3               conda-forge
    xz:               5.2.3-0               conda-forge
    zlib:             1.2.11-h470a237_3     conda-forge

Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done


(test-gdp) $ python -c "import geopandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rgommers/anaconda3/envs/test-gdp/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/home/rgommers/anaconda3/envs/test-gdp/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/home/rgommers/anaconda3/envs/test-gdp/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/rgommers/anaconda3/envs/test-gdp/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libjson-c.so.2: cannot open shared object file: No such file or directory
```

**Comment by ocefpaf** [comment]
Actually, latest `gdal` should already get `json-c 0.13`. You are getting a really old gdal there, `libgdal 2.1.4-9` go figure why conda is doing that :-/

I removed those versions and this worked for me:

```
conda create --name test-gdp python=3.6 geopandas
python -c 'import geopandas; print(geopandas.__version__)'
``` 

Please let me know if you are still experiencing this.

**Comment by rgommers** [comment]
Weird that I'm not getting the latest versions. I'll investigate. Thanks @ocefpaf

**Comment by ocefpaf** [comment]
> Weird that I'm not getting the latest versions. I'll investigate. Thanks @ocefpaf

Not weird, I removed those versions :smile:
(Sorry it was not clear in my message above)

**Comment by rgommers** [comment]
Tried again from scratch, seems to work as expected now.

**Comment by bgilbert5** [comment]
I'm still having this problem, I've tried to uninstall and re-install several times, most recently with miniconda.  So I wanted to see if anyone had any thoughts.  Here are my environments:

# Name                    Version                   Build  Channel
alabaster                 0.7.11                     py_3    conda-forge
asn1crypto                0.24.0                   py36_0
astroid                   1.6.5                    py36_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    2.1.3                      py_0    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5           py36h945400d_0
chardet                   3.0.4            py36h420ce6e_1
click                     6.7                        py_1    conda-forge
click-plugins             1.0.3                      py_1    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
cloudpickle               0.5.3                      py_0    conda-forge
colorama                  0.3.9                      py_1    conda-forge
conda                     4.5.9                    py36_0    conda-forge
conda-env                 2.6.0                h36134e3_1
console_shortcut          0.1.1                h6bb2dd7_3
cryptography              2.2.2            py36hfa6e2cd_0
curl                      7.61.0               h7602738_0
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.3.0                      py_0    conda-forge
descartes                 1.1.0                      py_2    conda-forge
docutils                  0.14                     py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.5                he025d50_1    conda-forge
fiona                     1.7.13           py36h2fc6367_2    conda-forge
freetype                  2.9.1                he8b6a0d_0    conda-forge
freexl                    1.0.5                hd288d7e_1    conda-forge
gdal                      2.2.4            py36h2fc6367_1    conda-forge
geopandas                 0.4.0                      py_0    conda-forge
geos                      3.6.2                he025d50_2    conda-forge
geotiff                   1.4.2                h2080a26_2    conda-forge
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.2               hbc3b0e7_1    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.6              py36h148d497_1
imagesize                 1.0.0                      py_1    conda-forge
intel-openmp              2018.0.3                      0
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.5.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.4                    py36_0    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   hfa6e2cd_0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kealib                    1.4.9                h4380d0d_2    conda-forge
keyring                   13.2.1                   py36_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
lazy-object-proxy         1.3.1            py36hfa6e2cd_0    conda-forge
libcurl                   7.61.0               h7602738_0
libgdal                   2.2.4                hf00ed0c_6    conda-forge
libiconv                  1.15                 hfa6e2cd_1    conda-forge
libnetcdf                 4.6.1                h183b1a9_3    conda-forge
libpng                    1.6.35               h7602738_0    conda-forge
libpq                     9.6.6                h14f23c8_0
libspatialindex           1.8.5                he025d50_2    conda-forge
libspatialite             4.3.0a              h582a839_21    conda-forge
libssh2                   1.8.0                hc4dcbb0_2    conda-forge
libtiff                   4.0.9                hf1753bf_1    conda-forge
libxml2                   2.9.8                haffccfe_2    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.2            py36had4c4a9_2
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.14           py36hfa6e2cd_0
mistune                   0.8.3            py36hfa6e2cd_2    conda-forge
mkl                       2018.0.3                      1
mkl_fft                   1.0.5                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
numpy                     1.14.3           py36h9fa60d3_2
numpy-base                1.14.3           py36h5c71026_0
numpydoc                  0.8.0                      py_1    conda-forge
openjpeg                  2.3.0                h25a6d84_3    conda-forge
openssl                   1.0.2o               hfa6e2cd_1    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.3           py36h830ac7b_1    conda-forge
pandoc                    2.2.2                hde52d81_1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       10.0.1                   py36_0
plotly                    3.1.0                      py_0    conda-forge
proj4                     4.9.3                hcf24537_7
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.6                    py36_0    conda-forge
psycopg2                  2.7.5            py36h74b6da3_1    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycosat                   0.6.3            py36h413d8a4_0
pycparser                 2.18             py36hd053e01_1
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pylint                    1.9.2                    py36_0    conda-forge
pyopenssl                 18.0.0                   py36_0
pyparsing                 2.2.0                      py_1    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0            py36h764d66f_6    conda-forge
pysal                     1.14.4.post1             py36_1    conda-forge
pysocks                   1.6.8                    py36_0
python                    3.6.5                h0c2934d_0
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pywin32                   223              py36hfa6e2cd_1
pywin32-ctypes            0.1.2                    py36_0    conda-forge
pyzmq                     17.0.0                   py36_3    conda-forge
qt                        5.6.2                h2639256_8    conda-forge
qtawesome                 0.4.4              pyh8a2030e_1    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.4.2              pyh8a2030e_1    conda-forge
requests                  2.18.4           py36h4371aae_1
retrying                  1.3.3                      py_2    conda-forge
rope                      0.10.7                     py_1    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
ruamel_yaml               0.15.37          py36hfa6e2cd_2
scipy                     1.1.0            py36h672f292_0
setuptools                39.2.0                   py36_0
shapely                   1.6.4            py36hc90234e_1    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0           py36h4db2310_1
snowballstemmer           1.2.1                      py_1    conda-forge
sphinx                    1.7.5                    py36_0    conda-forge
sphinxcontrib-websupport  1.1.0                    py36_0    conda-forge
spyder                    3.3.0                    py36_2    conda-forge
spyder-kernels            0.2.4                      py_1    conda-forge
sqlalchemy                1.2.10           py36hfa6e2cd_1    conda-forge
sqlite                    3.24.0               hb652765_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tornado                   5.1              py36hfa6e2cd_1    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.22             py36h276f60a_0
vc                        14.1                 h0510ff6_3
vs2015_runtime            15.5.2                        3
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                    py36_0    conda-forge
wheel                     0.31.1                   py36_0
win_inet_pton             1.0.1            py36he67d7fd_1
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.10.11                  py36_0    conda-forge
xerces-c                  3.2.0                h44c76bb_2
xz                        5.2.4                h2fa13f4_0    conda-forge
yaml                      0.1.7             

I get the following error when I try to run my script:

  File "C:/Users/Bert/Desktop/Bert Work/VIIRS/ViirsLoader.py", line 15, in <module>
    import geopandas as gpd

  File "C:\Users\Bert\Miniconda3\lib\site-packages\geopandas\__init__.py", line 4, in <module>
    from geopandas.io.file import read_file

  File "C:\Users\Bert\Miniconda3\lib\site-packages\geopandas\io\file.py", line 3, in <module>
    import fiona

  File "C:\Users\Bert\Miniconda3\lib\site-packages\fiona\__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path

  File "C:\Users\Bert\Miniconda3\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator

ImportError: DLL load failed: The specified module could not be found.   hc54c509_2
zlib                      1.2.11               h2fa13f4_3    conda-forge`

**Comment by ocefpaf** [comment]
Based on the number of packages you are getting from `defaults` there you are probably hitting https://github.com/conda/conda/issues/7626
