### ISSUE TITLE
Build alpha release 1.8a2 ?

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/fiona-feedstock#92]
Fiona 1.8a2 has some nice new features (https://github.com/Toblerity/Fiona/blob/master/CHANGES.txt), and it would make it easier to test those out (eg in combination with geopandas) if conda-forge would provide binaries. 
Would there be interest in that?

**Comment by ocefpaf** [comment]
> Would there be interest in that?

Yes. We actually have a test PR in #59 but with no success so far :-(

**Comment by jorisvandenbossche** [comment]
Hmm, not sure how I missed that PR since it has a quite obvious title ... :)

**Comment by ocefpaf** [comment]
Done in #59 

Please let me know if you find any issue with that package.
